/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View_JFrame;

import DBConnect.Chua_Bien;
import ToanBo_KhuyenMai.QL_ChiTiet_KhuyenMai_Panel;
import ToanBo_TaiKhoan.QL_TaiKhoan_TatCaPanel;
import ToanBo_TaiKhoan.QL_ChiTet_TaiKhoan_Panel;
import ToanBo_TaiKhoan.QL_TaiKhoan_NhanVien_Panel;
import ToanBo_TaiKhoan.QL_TaiKhoan_QuanLy_Panel;
import java.awt.BorderLayout;
import ToanBo_SanPham.QL_SanPham_ChiTiet_Panel;
import javax.swing.JOptionPane;
import ToanBo_BanHang.QL_BanHang_Panel;
import ToanBo_BanHang.Tao_Ma_QR;
import ToanBo_KhachHang.QL_KhachHang_TimKiem_Panel;
import ToanBo_NguyenLieu.QL_ChiTiet_NguyenLieu;
import ToanBo_TaiKhoan.QL_Login;
import ToanBo_TaiKhoan.Tai_Khoan;
import ToanBo_ThongKe.QL_ThongKe_DoanhThu_Panel;
import javax.swing.ImageIcon;
import ToanBo_TaiKhoan.QL_TaiKhoan;
import ToanBo_TaiKhoan.ThongTinCaNhan;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import ToanBo_HoatDong.QL_Hoa_Don_Panel;
import ToanBo_KhachHang.QL_KhachHang_JFrame;
import ToanBo_KhachHang.QL_KhachHang_Panel;

/**
 *
 * @author ADMIN
 */
public class TrangChu_NQL extends javax.swing.JFrame {
//
//    private TaiKhoan_4_O taiKhoan;
//    public static Tai_Khoan taiKhoan_NQL;
//    QL_Login QL_Log = new QL_Login();

    /**
     * Creates new form TrangChu_NQL
     */
    public TrangChu_NQL() { // TaiKhoan_4_O taiKhoan
//        this.taiKhoan = taiKhoan;
        initComponents();
        this.setLocationRelativeTo(this);
//        hienThiThongTinNguoiDung();

//        btn_LichSu.setEnabled(false);

        // Hiện Ảnh Cho Tài KHoản
        hienThiAnhTaiKhoan();
        // Hiện Thông Tin Cá Nhân
        CaiDat.setVisible(false); // Ẩn menu khi khởi động
        btn_CaiDat.addActionListener(e -> {
            boolean hienMenu = btn_CaiDat.isSelected();
            CaiDat.setVisible(hienMenu);
        });
    }

    public void hienThiAnhTaiKhoan() {
        QL_TaiKhoan dao = new QL_TaiKhoan();
        String maTK = Chua_Bien.Ma_TK; // Mã tài khoản hiện tại

        String duongDanAnh = dao.layDuongDanAnhTaiKhoan(maTK); // DAO trả về String

        int width = lb_HienThiAnh.getWidth();
        int height = lb_HienThiAnh.getHeight();

        if (duongDanAnh != null && !duongDanAnh.isEmpty()) {
            File file = new File(duongDanAnh);
            if (file.exists()) {
                ImageIcon icon = new ImageIcon(duongDanAnh);
                Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
                lb_HienThiAnh.setIcon(new ImageIcon(img));
            } else {
                System.out.println("⚠️ Đường dẫn ảnh không tồn tại: " + duongDanAnh);
                hienThiAnhMacDinh(width, height);
            }
        } else {
            hienThiAnhMacDinh(width, height);
        }
    }

    private void hienThiAnhMacDinh(int width, int height) {
        ImageIcon defaultIcon = new ImageIcon("src/icon/default-avatar.png");
        Image imgDefault = defaultIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lb_HienThiAnh.setIcon(new ImageIcon(imgDefault));
    }

//    private void hienThiThongTinNguoiDung() {
//        String path = taiKhoan.getAnh_TK();
//        if (path == null || path.isEmpty()) {
//            path = "src/images/default.png";
//        }
//
//        ImageIcon icon = new ImageIcon(path);
//        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
//        lb_HienThiAnh.setIcon(new ImageIcon(img)); // lblAvatar là JLabel đã đặt trong giao diện
//    }
    public void TatCa_VaiTro() {
        QL_TaiKhoan_TatCaPanel qltk_panel = new QL_TaiKhoan_TatCaPanel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qltk_panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    public void VaiTro_NhanVien() {
        QL_TaiKhoan_NhanVien_Panel qlnv_Panel = new QL_TaiKhoan_NhanVien_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlnv_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    public void VaiTro_QuanLy() {
        QL_TaiKhoan_QuanLy_Panel qlql_Panel = new QL_TaiKhoan_QuanLy_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlql_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThanhChucNang_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_BanHang = new javax.swing.JButton();
        btn_NguyenLieu = new javax.swing.JButton();
        btn_SanPham = new javax.swing.JButton();
        btn_TaiKhoan = new javax.swing.JButton();
        btn_KhachHang = new javax.swing.JButton();
        btn_ThongKeDoanhThu = new javax.swing.JButton();
        btn_KhuyenMai = new javax.swing.JButton();
        btn_LichSu = new javax.swing.JButton();
        TrangChungChuyen = new javax.swing.JPanel();
        lb_DanhMuc = new javax.swing.JLabel();
        CaiDat = new javax.swing.JPanel();
        btn_ThongTinCaNhap = new javax.swing.JButton();
        btn_DangXuat = new javax.swing.JButton();
        btn_TaoMa_QR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_CaiDat = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        lb_HienThiAnh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        ThanhChucNang_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logochinh.jpg"))); // NOI18N

        btn_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BanHang.png"))); // NOI18N
        btn_BanHang.setText("Bán Hàng");
        btn_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BanHangActionPerformed(evt);
            }
        });

        btn_NguyenLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/NguyenLieu.png"))); // NOI18N
        btn_NguyenLieu.setText("Nhập Hàng");
        btn_NguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NguyenLieuActionPerformed(evt);
            }
        });

        btn_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SanPham.png"))); // NOI18N
        btn_SanPham.setText("Sản Phẩm");
        btn_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamActionPerformed(evt);
            }
        });

        btn_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/TaiKhoan.png"))); // NOI18N
        btn_TaiKhoan.setText("Quản Lý Tài Khoản");
        btn_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaiKhoanActionPerformed(evt);
            }
        });

        btn_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KhachHang.png"))); // NOI18N
        btn_KhachHang.setText("Khách Hàng");
        btn_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhachHangActionPerformed(evt);
            }
        });

        btn_ThongKeDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Thong_Ke_Doanh_Thu.png"))); // NOI18N
        btn_ThongKeDoanhThu.setText("Thống Kê Doanh Thu");
        btn_ThongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeDoanhThuActionPerformed(evt);
            }
        });

        btn_KhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/KhuyenMai.png"))); // NOI18N
        btn_KhuyenMai.setText("Khuyến Mãi");
        btn_KhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhuyenMaiActionPerformed(evt);
            }
        });

        btn_LichSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/History.png"))); // NOI18N
        btn_LichSu.setText("Quản Lý Hoá Đơn");
        btn_LichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LichSuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThanhChucNang_PanelLayout = new javax.swing.GroupLayout(ThanhChucNang_Panel);
        ThanhChucNang_Panel.setLayout(ThanhChucNang_PanelLayout);
        ThanhChucNang_PanelLayout.setHorizontalGroup(
            ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ThanhChucNang_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_NguyenLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(btn_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_KhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        ThanhChucNang_PanelLayout.setVerticalGroup(
            ThanhChucNang_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhChucNang_PanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ThongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_LichSu)
                .addGap(73, 73, 73))
        );

        TrangChungChuyen.setBackground(new java.awt.Color(255, 255, 255));
        TrangChungChuyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TrangChungChuyenLayout = new javax.swing.GroupLayout(TrangChungChuyen);
        TrangChungChuyen.setLayout(TrangChungChuyenLayout);
        TrangChungChuyenLayout.setHorizontalGroup(
            TrangChungChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1128, Short.MAX_VALUE)
        );
        TrangChungChuyenLayout.setVerticalGroup(
            TrangChungChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_DanhMuc.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lb_DanhMuc.setText("Welcome to  Fake AL Fresco’s");

        btn_ThongTinCaNhap.setBackground(new java.awt.Color(255, 204, 204));
        btn_ThongTinCaNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThongTinCaNhap.setText("Cá Nhân");
        btn_ThongTinCaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhapActionPerformed(evt);
            }
        });

        btn_DangXuat.setText("Đăng Xuất");
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        btn_TaoMa_QR.setBackground(new java.awt.Color(204, 255, 204));
        btn_TaoMa_QR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TaoMa_QR.setText("Tạo QR");
        btn_TaoMa_QR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMa_QRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CaiDatLayout = new javax.swing.GroupLayout(CaiDat);
        CaiDat.setLayout(CaiDatLayout);
        CaiDatLayout.setHorizontalGroup(
            CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CaiDatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThongTinCaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaoMa_QR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CaiDatLayout.setVerticalGroup(
            CaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaiDatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ThongTinCaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_TaoMa_QR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        btn_CaiDat.setText("Cài Đặt");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tài Khoản"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_HienThiAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_HienThiAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_CaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThanhChucNang_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrangChungChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CaiDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThanhChucNang_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrangChungChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Sản Phẩm");
        QL_SanPham_ChiTiet_Panel qlspct_Panel = new QL_SanPham_ChiTiet_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlspct_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_SanPhamActionPerformed

    private void btn_NguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NguyenLieuActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Nhập Hàng");
        QL_ChiTiet_NguyenLieu qlnl_Panel = new QL_ChiTiet_NguyenLieu();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlnl_Panel, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_NguyenLieuActionPerformed

    private void btn_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhachHangActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Khách Hàng");
        QL_KhachHang_JFrame QL_KH = new QL_KhachHang_JFrame();
        QL_KH.setVisible(true);
        QL_KH.setAlwaysOnTop(true);
    }//GEN-LAST:event_btn_KhachHangActionPerformed

    private void btn_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BanHangActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quán Lý Bán Hàng");
        QL_BanHang_Panel qlbh = new QL_BanHang_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlbh, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_BanHangActionPerformed

    private void btn_ThongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeDoanhThuActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Thống Kê Doanh Thu");
        QL_ThongKe_DoanhThu_Panel tk = new QL_ThongKe_DoanhThu_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(tk, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_ThongKeDoanhThuActionPerformed

    private void btn_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaiKhoanActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quản Lý Tài Khoản");

        QL_ChiTet_TaiKhoan_Panel QL_TK = new QL_ChiTet_TaiKhoan_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(QL_TK, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_TaiKhoanActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
        QL_Login qllg = new QL_Login();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // ✅ Cập nhật trạng thái tài khoản về "Không hoạt động"
            int ketQua = qllg.capNhatTrangThai(Chua_Bien.Ma_TK, false); // 0 = Không hoạt động
            if (ketQua <= 0) {
                JOptionPane.showMessageDialog(this, "Không thể cập nhật trạng thái tài khoản!");
                return;
            }

            this.dispose(); // đóng giao diện hiện tại
            new Login().setVisible(true); // mở lại form đăng nhập
        }
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_KhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhuyenMaiActionPerformed
        // TODO add your handling code here:
        lb_DanhMuc.setText("Quản Lý Quản Lý Khuyến Mãi");
        QL_ChiTiet_KhuyenMai_Panel qlkm = new QL_ChiTiet_KhuyenMai_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlkm, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_KhuyenMaiActionPerformed

    private void btn_LichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LichSuActionPerformed
        // TODO add your handling code here:
        QL_Hoa_Don_Panel qlhd = new QL_Hoa_Don_Panel();
        TrangChungChuyen.removeAll();
        TrangChungChuyen.setLayout(new BorderLayout());
        TrangChungChuyen.add(qlhd, BorderLayout.CENTER);
        TrangChungChuyen.revalidate();
        TrangChungChuyen.repaint();
    }//GEN-LAST:event_btn_LichSuActionPerformed

    private void btn_ThongTinCaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhapActionPerformed
        // TODO add your handling code here:
        ThongTinCaNhan tncn = new ThongTinCaNhan();
        tncn.setVisible(true); // Hiển thị JFrame
        tncn.setLocationRelativeTo(null); // Canh giữa màn hình (tuỳ chọn)
    }//GEN-LAST:event_btn_ThongTinCaNhapActionPerformed

    private void btn_TaoMa_QRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMa_QRActionPerformed
        // TODO add your handling code here:
        Tao_Ma_QR Tao_MaQR = new Tao_Ma_QR();
        Tao_MaQR.setVisible(true); // Hiển thị JFrame
        Tao_MaQR.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_TaoMa_QRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu_NQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        taiKhoan_NQL = QL_Log.getTaiKhoanTheoEmail(emailDangNhap);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu_NQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaiDat;
    private javax.swing.JPanel ThanhChucNang_Panel;
    private javax.swing.JPanel TrangChungChuyen;
    private javax.swing.JButton btn_BanHang;
    private javax.swing.JToggleButton btn_CaiDat;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_KhachHang;
    private javax.swing.JButton btn_KhuyenMai;
    private javax.swing.JButton btn_LichSu;
    private javax.swing.JButton btn_NguyenLieu;
    private javax.swing.JButton btn_SanPham;
    private javax.swing.JButton btn_TaiKhoan;
    private javax.swing.JButton btn_TaoMa_QR;
    private javax.swing.JButton btn_ThongKeDoanhThu;
    private javax.swing.JButton btn_ThongTinCaNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb_DanhMuc;
    private javax.swing.JLabel lb_HienThiAnh;
    // End of variables declaration//GEN-END:variables
}
